config/routes.rb
Rails.application.routes.draw do

  resources :articles
  namespace :users do
    get 'dashboard/index'
  end
  devise_for :users do
  end
  root 'home#index'
  get 'about', to: 'home#about'
  get 'campaings', to: 'home#campaign'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: {minimum: 8, maximum: 50}
  validates :description, presence: true, length: {minimum: 25}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaign</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/about.html.erb
<div class="container" align="center">
  <div class="row">
    <div class="col-md-12">
      <h3>About Us</h3>
      <%= image_tag 'https://i1.wp.com/holytrinity.to/wp-content/uploads/2020/08/miguel-a-amutio-TqOFeBqnqrI-unsplash-scaled.jpg?resize=930%2C620&ssl=1', height: '200px', width: '100%'%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p>Kentaa is a crowdfunding platform for non-profits and other initiatives that want to change society for the better. We want to offer them a new way to raise money. Kentaa stimulates everyone to work together on a healthy society.</p>
      <p>Kentaa is an online fundraising expert that helps people and organisations strive for equal opportunities for all and make the world a better place. We offer smart online platforms and tools to allow as many people as possible to raise funds for social causes successfully.
        Additionally, we offer advice for successful crowdfunding, event fundraising, peer-to-peer fundraising and online collection campaigns. Our clients include charities, universities, museums, care facilities and sports clubs.
        Kentaa has a social mission to help social good organisations create online revenue to realise their dreams. Helping them reach these goals is in our DNA.</p>
    </div>
  </div>
</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid" style="height:300px; background-image: url('https://image.freepik.com/free-photo/donate-sign-charity-campaign_53876-127165.jpg'); background-repeat: no-repeat; background-size: cover;">
  <div class="container">
    <h1 class="display-4">Campaign AG</h1>
    <p class="lead">Our focus in rising funding campaigning.</p>
  </div>
</div>




<div class="row row-cols-1 row-cols-md-3">
  <% @articles.each do |campaign| %>
    <div class="col-md-4" align="center">
      <div class="card h-100" style="background-color: lightblue; border-radius: 10px; padding: 10px">
        <img src="" width="200px" height="150px" alt="hello" />
        <div class="card-body">
          <h5 class="card-title"> <%= campaign.title %> </h5>
          <p class="card-text">Size: <%= campaign.description %></p>
        </div>
        <%= link_to 'More', article_path(campaign), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campaign</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navigation' %>
  <hr class="my-4">
  <div class="center container">
    <%= yield %>
  </div>
  <hr class="my-4">
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="text-center text-white">
  <div>
    <h3 class="center">Campaign</h3>
    <p>Contact us in any of these social media</p>
  </div>
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a href="https://www.facebook.com/" class="fa fa-facebook"></a>
      <!-- Twitter -->
      <a href="https://www.twitter.com/" class="fa fa-twitter"></a>
      <!-- Linkedin -->
      <a href="https://www.linkedin.com/" class="fa fa-linkedin"></a>
      <!-- GoogleMail -->
      <a href="https://www.linkedin.com/" class="fa fa-google"></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3">
    © <%= Time.now.year %> Copyright:
    <%= link_to 'Kelmend Imeri', "https://www.facebook.com/kelmendimeri", class: 'text-dark'%>

  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Campaign</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <% if !user_signed_in? %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <!--        <li><%#= link_to 'Create User', new_user_registration_path %></li>  -->
      <% else %>
        <li><%= link_to 'Campaigns', articles_path %></li>
        <li><%= link_to 'Create Campaign', new_article_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/dashboard/index.html.erb
<h1>Users::Dashboard#index</h1>
<p>Find me in app/views/users/dashboard/index.html.erb</p>